### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by ReinierAarnink1996** [loldudester/analogue-timestamps#1]
I turned it on and I don't see any timestamps in any chatform..

**Comment by Hannah-GBS** [comment]
Not sure why I didn't get a notification for this issue. Sorry about that.

Apparently Runelite changed how their timestamps worked so the script callback I was also using no longer exists. I haven't been playing much in the last year so I didn't notice. I am working on a fix for it now.

**Comment by ReinierAarnink1996** [comment]
> Not sure why I didn't get a notification for this issue. Sorry about that.
> 
> Apparently Runelite changed how their timestamps worked so the script callback I was also using no longer exists. I haven't been playing much in the last year so I didn't notice. I am working on a fix for it now.

Curious to see what it actually looks like. The digital timestamps take up more space I bet, also looks kinda ugly.

**Comment by Hannah-GBS** [comment]
![java_byxv007cI3](https://user-images.githubusercontent.com/7504779/151924290-b1a8fb6b-6a7d-40f8-9105-190a2bd5f93a.png)

It looks like this. I use both timestamps because the analogue ones are barely readable.

"Why did you make this plugin in that case?" you may ask.

Idk.

Anyway I've submitted a fix to the plugin hub, I'll close this issue when it's accepted.

**Comment by Hannah-GBS** [comment]
The update has been merged and the plugin should now be functional again.

**Comment by ReinierAarnink1996** [comment]
> ![java_byxv007cI3](https://user-images.githubusercontent.com/7504779/151924290-b1a8fb6b-6a7d-40f8-9105-190a2bd5f93a.png)
> 
> It looks like this. I use both timestamps because the analogue ones are barely readable.
> 
> "Why did you make this plugin in that case?" you may ask.
> 
> Idk.
> 
> Anyway I've submitted a fix to the plugin hub, I'll close this issue when it's accepted.

It is actually pretty readable. I dont need to precisely know the time.

Could you maybe make the clock black and have an arrow with colour green or white or red and the other one.. idk, white? I think that looks cool
